#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Your Name'
        hostname: ubuntu-desktop
        username: Ubuntu-User
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3' #install mkpasswd and run mkpasswd yourpassword 
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
        - okular
        - spotify
    snaps:
        - name: keepassxc
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

